### PR TITLE
import PropTypes from 'prop-types';

### PR DESCRIPTION
**Pull request by RobertSasak**
Make it compatible with latest react versions.

### CODE REVIEW

**Comment by RobertSasak** [comment]
@Progoogler Can you please merge this?

**Comment by ricocrescenzio95** [comment]
It would be better to merge this pull request, in my project the library doesn't work at all 😔

**Comment by RobertSasak** [comment]
@Friendly-Robot This PR was never merged. Can you please actually merge it?

**Comment by KnapSac** [comment]
When I cloned this repo, it turned out that the code in the camera.js file wasn't actually changed to what this PR is proposing, can it be changed? It would make upgrading to a newer React Native version a lot easier.

**Pull request merged**
